-- Создаем базу данных для тестовых данных
CREATE DATABASE IF NOT EXISTS official_datasets;

-- Создаем таблицу hits (одна из официальных тестовых таблиц)
CREATE TABLE IF NOT EXISTS official_datasets.hits
(
    WatchID UInt64,
    JavaEnable UInt8,
    Title String,
    GoodEvent Int16,
    EventTime DateTime,
    EventDate Date,
    CounterID UInt32,
    ClientIP UInt32,
    RegionID UInt32,
    UserID UInt64,
    CounterClass Int8,
    OS UInt8,
    UserAgent UInt8,
    URL String,
    Referer String,
    Refresh UInt8,
    RefererCategoryID UInt16,
    RefererRegionID UInt32,
    URLCategoryID UInt16,
    URLRegionID UInt32,
    ResolutionWidth UInt16,
    ResolutionHeight UInt16,
    ResolutionDepth UInt8,
    FlashMajor UInt8,
    FlashMinor UInt8,
    FlashMinor2 String,
    NetMajor UInt8,
    NetMinor UInt8,
    UserAgentMajor UInt16,
    UserAgentMinor FixedString(2),
    CookieEnable UInt8,
    JavascriptEnable UInt8,
    IsMobile UInt8,
    MobilePhone UInt8,
    MobilePhoneModel String,
    Params String,
    IPNetworkID UInt32,
    TraficSourceID Int8,
    SearchEngineID UInt16,
    SearchPhrase String,
    AdvEngineID UInt8,
    IsArtifical UInt8,
    WindowClientWidth UInt16,
    WindowClientHeight UInt16,
    ClientTimeZone Int16,
    ClientEventTime DateTime,
    SilverlightVersion1 UInt8,
    SilverlightVersion2 UInt8,
    SilverlightVersion3 UInt32,
    SilverlightVersion4 UInt16,
    PageCharset String,
    CodeVersion UInt32,
    IsLink UInt8,
    IsDownload UInt8,
    IsNotBounce UInt8,
    FUniqID UInt64,
    OriginalURL String,
    HID UInt32,
    IsOldCounter UInt8,
    IsEvent UInt8,
    IsParameter UInt8,
    DontCountHits UInt8,
    WithHash UInt8,
    HitColor FixedString(1),
    LocalEventTime DateTime,
    Age UInt8,
    Sex UInt8,
    Income UInt8,
    Interests UInt16,
    Robotness UInt8,
    RemoteIP UInt32,
    WindowName Int32,
    OpenerName Int32,
    HistoryLength Int16,
    BrowserLanguage FixedString(2),
    BrowserCountry FixedString(2),
    SocialNetwork String,
    SocialAction String,
    HTTPError UInt16,
    SendTiming Int32,
    DNSTiming Int32,
    ConnectTiming Int32,
    ResponseStartTiming Int32,
    ResponseEndTiming Int32,
    FetchTiming Int32,
    SocialSourceNetworkID UInt8,
    SocialSourcePage String,
    ParamPrice Int64,
    ParamOrderID String,
    ParamCurrency FixedString(3),
    ParamCurrencyID UInt16,
    OpenstatServiceName String,
    OpenstatCampaignID String,
    OpenstatAdID String,
    OpenstatSourceID String,
    UTMSource String,
    UTMMedium String,
    UTMCampaign String,
    UTMContent String,
    UTMTerm String,
    FromTag String,
    HasGCLID UInt8,
    RefererHash UInt64,
    URLHash UInt64,
    CLID UInt32
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(EventDate)
ORDER BY (CounterID, EventDate, intHash32(UserID))
SAMPLE BY intHash32(UserID);

-- Создаем таблицу visits (вторая официальная тестовая таблица)
CREATE TABLE IF NOT EXISTS official_datasets.visits
(
    CounterID UInt32,
    StartDate Date,
    Sign Int8,
    IsNew UInt8,
    VisitID UInt64,
    UserID UInt64,
    StartTime DateTime,
    Duration UInt32,
    UTCStartTime DateTime,
    PageViews Int32,
    Hits Int32,
    IsBounce UInt8,
    Referer String,
    StartURL String,
    RefererDomain String,
    StartURLDomain String,
    EndURL String,
    LinkURL String,
    LinkDomain String,
    IsLink UInt8,
    Title String,
    Description String,
    Keywords String,
    OpenStatServiceName String,
    OpenStatCampaignID String,
    OpenStatAdID String,
    OpenStatSourceID String,
    UTMSource String,
    UTMMedium String,
    UTMCampaign String,
    UTMContent String,
    UTMTerm String,
    FromTag String,
    HasGCLID UInt8,
    RefererHash UInt64,
    StartURLHash UInt64,
    LinkURLHash UInt64
)
ENGINE = CollapsingMergeTree(Sign)
PARTITION BY toYYYYMM(StartDate)
ORDER BY (CounterID, StartDate, intHash32(UserID), VisitID)
SAMPLE BY intHash32(UserID);

-- Вставляем тестовые данные (упрощенные, как в официальных примерах)
INSERT INTO official_datasets.hits VALUES 
(123456789, 1, 'Main Page', 1, now(), today(), 12345, 3232235777, 1, 987654321, 1, 1, 1, 'http://example.com/', 'http://google.com', 0, 1, 1, 1, 1, 1920, 1080, 24, 1, 1, '', 1, 1, 1, '1', 1, 1, 0, 0, '', 'param=value', 1, 1, 1, 'clickhouse test', 0, 0, 1920, 1080, 0, now(), 0, 0, 0, 0, 'UTF-8', 1, 0, 0, 1, 123456789, 'http://example.com/', 1, 0, 0, 0, 0, 0, 'R', now(), 25, 1, 3, 123, 0, 3232235777, 0, 0, 5, 'en', 'US', 'facebook', 'like', 200, 100, 10, 20, 30, 40, 50, 1, 'page', 100, 'order123', 'USD', 840, 'service', 'campaign', 'ad', 'source', 'google', 'cpc', 'campaign', 'content', 'term', 'tag', 0, 123456789, 987654321, 123);

INSERT INTO official_datasets.visits VALUES 
(12345, today(), 1, 1, 123456789, 987654321, now(), 3600, now(), 5, 10, 0, 'http://google.com', 'http://example.com/', 'google.com', 'example.com', 'http://example.com/end', 'http://example.com/link', 'example.com', 1, 'Example Page', 'Test description', 'clickhouse,database,test', 'service', 'campaign', 'ad', 'source', 'google', 'cpc', 'campaign', 'content', 'term', 'tag', 0, 123456789, 987654321, 123456789);